//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Operacoes.ServicoOperacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoOperacao.IOperacao")]
    public interface IOperacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Somar", ReplyAction="http://tempuri.org/IOperacao/SomarResponse")]
        double Somar(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Somar", ReplyAction="http://tempuri.org/IOperacao/SomarResponse")]
        System.Threading.Tasks.Task<double> SomarAsync(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Subtrair", ReplyAction="http://tempuri.org/IOperacao/SubtrairResponse")]
        double Subtrair(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Subtrair", ReplyAction="http://tempuri.org/IOperacao/SubtrairResponse")]
        System.Threading.Tasks.Task<double> SubtrairAsync(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Divisao", ReplyAction="http://tempuri.org/IOperacao/DivisaoResponse")]
        double Divisao(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Divisao", ReplyAction="http://tempuri.org/IOperacao/DivisaoResponse")]
        System.Threading.Tasks.Task<double> DivisaoAsync(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Multiplicacao", ReplyAction="http://tempuri.org/IOperacao/MultiplicacaoResponse")]
        double Multiplicacao(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/Multiplicacao", ReplyAction="http://tempuri.org/IOperacao/MultiplicacaoResponse")]
        System.Threading.Tasks.Task<double> MultiplicacaoAsync(double valor1, double valor2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/CaixaAlta", ReplyAction="http://tempuri.org/IOperacao/CaixaAltaResponse")]
        string CaixaAlta(string pTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/CaixaAlta", ReplyAction="http://tempuri.org/IOperacao/CaixaAltaResponse")]
        System.Threading.Tasks.Task<string> CaixaAltaAsync(string pTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/CaixaBaixa", ReplyAction="http://tempuri.org/IOperacao/CaixaBaixaResponse")]
        string CaixaBaixa(string pTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacao/CaixaBaixa", ReplyAction="http://tempuri.org/IOperacao/CaixaBaixaResponse")]
        System.Threading.Tasks.Task<string> CaixaBaixaAsync(string pTexto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacaoChannel : WCF_Operacoes.ServicoOperacao.IOperacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacaoClient : System.ServiceModel.ClientBase<WCF_Operacoes.ServicoOperacao.IOperacao>, WCF_Operacoes.ServicoOperacao.IOperacao {
        
        public OperacaoClient() {
        }
        
        public OperacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Somar(double valor1, double valor2) {
            return base.Channel.Somar(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<double> SomarAsync(double valor1, double valor2) {
            return base.Channel.SomarAsync(valor1, valor2);
        }
        
        public double Subtrair(double valor1, double valor2) {
            return base.Channel.Subtrair(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<double> SubtrairAsync(double valor1, double valor2) {
            return base.Channel.SubtrairAsync(valor1, valor2);
        }
        
        public double Divisao(double valor1, double valor2) {
            return base.Channel.Divisao(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<double> DivisaoAsync(double valor1, double valor2) {
            return base.Channel.DivisaoAsync(valor1, valor2);
        }
        
        public double Multiplicacao(double valor1, double valor2) {
            return base.Channel.Multiplicacao(valor1, valor2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicacaoAsync(double valor1, double valor2) {
            return base.Channel.MultiplicacaoAsync(valor1, valor2);
        }
        
        public string CaixaAlta(string pTexto) {
            return base.Channel.CaixaAlta(pTexto);
        }
        
        public System.Threading.Tasks.Task<string> CaixaAltaAsync(string pTexto) {
            return base.Channel.CaixaAltaAsync(pTexto);
        }
        
        public string CaixaBaixa(string pTexto) {
            return base.Channel.CaixaBaixa(pTexto);
        }
        
        public System.Threading.Tasks.Task<string> CaixaBaixaAsync(string pTexto) {
            return base.Channel.CaixaBaixaAsync(pTexto);
        }
    }
}
